config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :categories, param: :kind,  only: [] do
    resources :entries, only: :index
  end

  resources :sessions, only: %i(create index)
  resources :prohibitions, only: %i(index create destroy update)
  resources :users, only: %i(destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  enum kind: {general:0 , social:1 ,economics:2, fun:3, life:4, knowledge:5, it:6, entertainment:7, game:8}

  has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :category
end

app/models/prohibition.rb
class Prohibition < ApplicationRecord
  belongs_to :user

  enum prohibition_type: {domain: 'domain', title: 'title'}

  scope :is_active, -> { where(activated: true) }

  def prohibit?(target)
    target.include?(word)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :prohibitions, dependent: :destroy

  devise :omniauthable, :timeoutable, omniauth_providers: %i(hatena)

  def prohibit_entry?(entry)
    prohibitions.is_active.map{|prohibition|
      (prohibition.prohibit?(entry.url) && prohibition.domain?) || (prohibition.prohibit?(entry.title) && prohibition.title?)
    }.any?
  end

  def self.from_omniauth(omniauth_hash)
    find_or_create_by(provider: omniauth_hash['provider'], uid:omniauth_hash['uid'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def set_user
    @user = current_user
  end
end

app/controllers/entries_controller.rb
require 'oauth'
require 'json'

class EntriesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_user

  def index
    @categories = Category.all
    if params[:category_kind]
      @selected_category = Category.find_by(kind: params[:category_kind])
      session[:last_shown_category] = params[:category_kind]
    else
      @selected_category = Category.find_by(kind: session[:last_shown_category])
    end
    @selected_category = Category.first unless @selected_category
    @entries = @selected_category.entries.reject{|entry| @user.prohibit_entry?(entry)}
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def hatena
    @user = User.from_omniauth(request.env["omniauth.auth"])

    sign_in @user

    redirect_to category_entries_path(Category.first.kind)
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/prohibitions_controller.rb
class ProhibitionsController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!
  before_action :set_prohibition, only: %i(update destroy)

  def index
    @prohibitions = @user.prohibitions.sort_by(&:prohibition_type)
  end

  def create
    @user.prohibitions.create(prohibition_params)
    redirect_to prohibitions_path
  end

  def destroy
    @prohibition.destroy!
    redirect_to prohibitions_path
  end

  def update
    @prohibition.update(activated: !@prohibition.activated)
    redirect_to prohibitions_path
  end

  private

  def set_prohibition
    @prohibition = Prohibition.find(params[:id])
  end

  def prohibition_params
    params.require(:prohibition).permit(:prohibition_type, :word)
  end
end

app/controllers/sessions_controller.rb
require 'oauth'
require 'json'

class SessionsController < ApplicationController

  def index
    if session[:last_shown_category]
      category = Category.find_by_kind(session[:last_shown_category])
      redirect_to category_entries_path(category.kind) if user_signed_in?
    else
      redirect_to category_entries_path(Category.first.kind) if user_signed_in?
    end
  end

  def create
    @consumer = OAuth::Consumer.new(
      ENV['HATENA_CONSUMER_KEY'],
      ENV['HATENA_CONSUMER_SECRET'],
      site: '',
      request_token_path: 'https://www.hatena.com/oauth/initiate',
      access_token_path: 'https://www.hatena.com/oauth/token',
      authorize_path: 'https://www.hatena.ne.jp/oauth/authorize')

    request_token = @consumer.get_request_token({oauth_callback: ENV['HATENA_CALLBACK_URL']}, scope: 'read_public')

    session[:request_token] = request_token.token
    session[:request_token_secret] = request_token.secret

    redirect_to request_token.authorize_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def destroy
    @user.destroy!

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/prohibitions_helper.rb
module ProhibitionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.haml
%li
  - if category == selected
    = link_to t(".#{category.kind}"), category_entries_path(category.kind), class: 'selected'
  - else
    = link_to t(".#{category.kind}"), category_entries_path(category.kind)

app/views/entries/_entry.html.haml
%article{class: "entry"}
  %p
    %h3= link_to(entry.title, entry.url)
    %span{class:"bookmark-count"}= link_to "#{entry.bookmark_count}users", "http://b.hatena.ne.jp/entry/#{entry.url}"

app/views/entries/index.html.haml
= render partial: :entry, collection: @entries

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Hateblocker
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body

  %header
    %nav{class:"navbar navbar-default"}
      .container-fluid
        .navbar-header
          = link_to 'はてブロッカー(β)', root_path, class: 'navbar-brand'
        - if @user
          %ul{class:"nav navbar-nav navbar-right"}
            %li
              %p{class:"navbar-text"}
                = @user.uid
            %li
              = link_to '禁止ワード管理', prohibitions_path
            %li{class:"btn-danger"}
              = link_to 'アカウント削除', user_path(@user), method: :delete, data: {confirm: 'Are you sure?'}
        %ul{class:"nav navbar-nav"}
          = render partial: :category, collection: @categories, locals: { selected: @selected_category }
    - if @user.nil?
      = form_for(:sessions, url: :sessions) do |f|
        %p
          = link_to "はてなIDでログイン", user_hatena_omniauth_authorize_path, class: "btn btn-lg btn-primary"

  %p{class:"notice"}
    = notice
  %p{class:"alert"}
    = alert

  %main{id:"main"}
    = yield

app/views/prohibitions/_prohibition.html.haml
%tr
  %th
  %th
    = prohibition.word
  %th
    - if prohibition.activated?
      = button_to "無効", prohibition_path(prohibition), {method: :put, class: 'activate_switch'}
    - else
      = button_to "有効", prohibition_path(prohibition), {method: :put, class: 'activate_switch'}
  %th
    = link_to '削除', prohibition_path(prohibition), method: :delete

app/views/prohibitions/index.html.haml
%h4
  ブロックした要素一覧

%table{class:"table table-hover"}
  %thead
    %tr
      %th
        ドメイン
      %th
      %th
      %th

  %tbody
    = render partial: :prohibition, collection: @prohibitions.select{|p|p.domain?}

  %thead
    %tr
      %th
        タイトル
      %th
      %th
      %th

  %tbody
    = render partial: :prohibition, collection: @prohibitions.select{|p|p.title?}


= form_for :prohibition  do |f|
  %h4>
    ブロック要素の追加
  .form-group
    = f.label :prohibition_type, '禁止タイプ'
    = f.select :prohibition_type, [['URLの一部', :domain],['タイトルの一部', :title]], {} , {id: 'prohibition_type', class: 'form-control'}

  .form-group
    = f.label :word, '禁止ワードまたは禁止ドメイン'
    = f.text_field :word, id: :input_word, class: 'form-control'

  = f.submit 'add'